### PR TITLE
Fix-local-install-1

### LINKED ISSUE #8: [Damaris Plugin] fix for some build errors

### LINKED ISSUE #14: [damaris plugin] remove non-standard headers
`bits/stdc++.h` is a non-standard header specific to the GNU C++ library (libstdc++).

### LINKED ISSUE #15: [damaris plugin] non POD error with `string` in `va_arg`
The `va_arg` macro is a low-level C mechanism. It works by performing a simple memory offset based on the size of the provided type. Because a `std::string` is a complex C++ object (non-POD), it has a copy constructor and internal pointers that `va_arg` simply cannot handle.

Fix: replace `va_arg(args, string)` by `va_arg(args, const char*)`

### PR DESCRIPTION
**Pull request by Yushan-Wang**
!!!INSERT YOUR DESCRIPTION HERE!!!

# List of things to check before making a PR

Before merging your code, please check the following:

* [ ] you have added a line describing your changes to the Changelog;
* [ ] you have added unit tests for any new or improved feature;
* [ ] in case you updated dependencies, you have checked pdi/docs/CheckList.md;
* [x] in case of a change in pdi.h, this same change must be reflected in no-pdi/include/pdi.h;
* you have checked your code format:
  - [x] you have checked that you respect all conventions specified in CONTRIBUTING.md;
  - [x] you have checked that the indentation and formatting conforms to the `.clang-format`;
  - [x] you have documented with doxygen any new or changed function / class;
* you have correctly updated the copyright headers:
  - [x] your institution is in the copyright header of every file you (substantially) modified;
  - [x] you have checked that the end-year of the copyright there is the current one;
* you have updated the AUTHORS file:
  - [x] you have added yourself to the AUTHORS file;
  - [x] if this is a new contribution, you have added it to the AUTHORS file;
* you have added everything to the user documentation:
  - [ ] any new CMake configuration option;
  - [ ] any change in the yaml config;
  - [ ] any change to the public or plugin API;
  - [ ] any other new or changed user-facing feature;
  - [ ] any change to the dependencies;
* you have correctly linked your MR to one or more issues:
  - [x] your MR solves an identified issue;
  - [x] your commit contain the `Fix #issue` keyword to autoclose the issue when merged.

### CODE REVIEW

**Review by endamlabin — COMMENTED** [review]
Copyright update have been done only on .cxx files, while .h files still have old years. Ii it the standard in PDI? If it normal then it all OK for me!

**Review by endamlabin — APPROVED** [review]

**Review by endamlabin — APPROVED** [review]

**Review by endamlabin — APPROVED** [review]

**Review by endamlabin — APPROVED** [review]
Completed with "[remove bits/stdc++ header](https://github.com/jmorice91/pdi/pull/13/changes/80fca1e876f67b57bddf85090d8ed46d0ce9ab12)" commit

**Review by endamlabin — APPROVED** [review]

File: plugins/damaris/example/example.c [hunk 1]
```diff
@@ -162,107 +162,113 @@ int main(int argc, char* argv[])
 	PC_tree_t conf = PC_parse_path(argv[1]);
 
 	MPI_Comm main_comm = MPI_COMM_WORLD;
+	int world_size;
+	MPI_Comm_size(MPI_COMM_WORLD, &world_size);
+	if (world_size != 4) {
+		fprintf(stderr, "Please use 4 mpi processes in total\n");
+		exit(1);
+	}
```
Comment (jmorice91) [inline plugins/damaris/example/example.c:170]: Here, we give an example of the damaris plugin. Perhaps, fixed the number of MPI  is not a good idea.

I suggest to discuss about this point before the rewriting of the example.

**Review by jmorice91 — COMMENTED** [review]
the damaris_plugin branch is updated . We need a rebase (I revert a commit in this branch)
Look good.

**Comment by jmorice91** [comment]
> Copyright update have been done only on .cxx files, while .h files still have old years. Ii it the standard in PDI? If it normal then it all OK for me!

The year of the copyright is by file. We only change the copyright if the file is changed  during the year.

File: plugins/damaris/example/example.c (hunk 1 above)
Comment (endamlabin) [reply plugins/damaris/example/example.c:170]: Yes I agree not to fixe the number of MPI ranks. Moreover, that number in general (for this example) is a multiple of 3 + dc (number of dedicated cores). It might be 7, etc.

But we have to find a way to inform the user about it.

**Review by endamlabin — APPROVED** [review]
